Changes to error handling in dailyDiscovery and searchProducts
NCMoseley/shop-hopper-api pull request #115
Opened 2022-01-05 21:50 UTC by BenMcLoughlin

On the front end if I can receive and error string and code separately it makes it easier to show it on the screen.

2022-01-05 21:52 UTC, BenMcLoughlin commented on backend/utils/auth/validateUser.js
> +        console.log('token: ', token);
whoops, this should be removed

2022-01-05 21:53 UTC, BenMcLoughlin commented on backend/utils/auth/validateUser.js
> +            if (await emailExists(decoded.email)) {
I needed a try catch here because the request would hang up and not return anything if the email couldnt be found.

2022-01-05 21:53 UTC, BenMcLoughlin commented on backend/utils/auth/validateUser.js
> +            return res.status(403).json({ error: { code: '403', message: 'Login to View Page' } });
This is the structure thats nice for the front end because I can set it directly in state, eg. setState({error})

2022-01-05 21:54 UTC, BenMcLoughlin commented on backend/utils/products/cleanString.js
> +
If no string is passed the code hangs up but I'm not sure if the search should be cancelled or allowed to proceed. Here its allowed to go ahead as an empty string.

2022-01-05 21:54 UTC, BenMcLoughlin commented on package.json
> +        "ngrok": "^4.2.2",
whoops, I meant to add this to the back end.

2022-01-07 18:35 UTC, NCMoseley requested changes

2022-01-07 18:35 UTC, NCMoseley commented on backend/utils/auth/validateUser.js
> +        console.log('token: ', token);
leave it for now

2022-01-07 18:35 UTC, NCMoseley commented on package.json
> +        "ngrok": "^4.2.2",
Remove this

2022-01-07 18:35 UTC, NCMoseley commented on pages/api/addShops/index.js
>          return true;
Do you need these changes, or is this old?

2022-01-07 18:35 UTC, NCMoseley commented on pages/api/searchProducts/index.js
>                      [column]: metric
Is this intentional?

2022-01-07 18:35 UTC, NCMoseley commented on pages/api/updateProducts/sanitize/products.js
> +<<<<<<< HEAD
Haha I'm glad I took the time to read this far. I don't know why we get some many damn Merge Conflicts

2022-01-07 18:39 UTC, BenMcLoughlin commented on pages/api/updateProducts/sanitize/products.js
> +<<<<<<< HEAD
Done

2022-01-07 19:27 UTC, merged